# Generated by Django 3.2 on 2021-12-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20211220_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
