# Generated by Django 3.2 on 2021-12-20 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0005_alter_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
