# Generated by Django 3.2 on 2022-04-05 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0008_alter_booking_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
