# Generated by Django 3.2 on 2022-04-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_alter_booking_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
    ]
